name: greetings_card
description: "An Eid Greetings Card Generator app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  permission_handler: ^10.4.0
  path_provider: ^2.1.1
  path: ^1.8.3
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/